version: '3.8'

services:
  webflux-app:
    build: .
    image: imukh1983/pi-shaped-workshop-indrajeetmukherjee:day1
    container_name: spring-webflux
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
